### ISSUE TITLE
slowNumericInput up/down arrow

### ISSUE THREAD

**Issue by mingsnu** [homerhanumat/shinyCustom#1]
Do you know why the outlook of `slowNumericInput` is different with that of `numericInput`? 
The `numericInput` widget includes two arrows on the right side and the user can use up/down arrows to increase/decrease the number.
Thank you!

**Comment by homerhanumat** [comment]
Yes, I know why, and I fixed the issue in the package customShiny and pushed to GitHub.  If you use install the current version of the package it should work as desired.  Thanks for pointing it out!
