### ISSUE TITLE
patient inputs for sliders?

### ISSUE THREAD

**Issue by fawda123** [homerhanumat/shinyCustom#2]
Is it feasible to have `customSliderInput` receive patient inputs like `customNumericInput`?  The slider delay is helpful but I would prefer the slider to update when focus is shifted.

**Comment by homerhanumat** [comment]
I looked at this a bit, but don't think it's feasible.  My JavaScript is not up to the task of getting the Ion Range Sliders to recognize and handle events like input or focusout.

But don't users expect sliders to work by only by changing position of the marker?  They might be confused by a patient slider.

**Comment by fawda123** [comment]
Yea I guess what I meant was that I was having issues with sliders selecting options while still selected with the mouse. It would be good to have it select input only after not clicking the mouse.

**Comment by homerhanumat** [comment]
I'm not sure what you mean.  Is there an example you can show me (maybe a shiny app online)?

**Comment by fawda123** [comment]
https://beckmw.shinyapps.io/swmp_agg/

This app lets you select a date range using a slider.  You'll notice that the plots update when you move the slider while it's still selected with the mouse.  I'd like it to select the date only after it's not selected with the mouse, i.e., you select the slider, move it, unselect, then plot updates.  It should not update anything in between the first and final selection.

**Comment by homerhanumat** [comment]
Yes, I see now.  Of course the way Shiny developers usually answered the questions of this sort is to suggest a constructing a "Submit" action button.  You make all of your desired changes in through slider, checkboxes, etc., then press Submit.  But I guess you've thought of that already.

I notice that the date-range slider updates only the plots, not the tables.  Is that your intention?

**Comment by fawda123** [comment]
I could add a 'submit' button but was hoping there was some work-around.  I would prefer not having the extra step of clicking 'submit'.  It's not a major issue and was just curious if you had any thoughts.  

And thanks for the heads up on the tables, those should be updated with the sliders as well.

**Comment by homerhanumat** [comment]
@fawda123 , check out the patientSlider branch of my repo:

    devtools::install_github("homerhanumat/ShinyCustom", ref = "patientSlider")

I believe it will do essentially what you want.  Shiny won't update the value from the slider until the "focusout" event occurs on the slider, e.g., the user clicks somewhere outside the slider.  You still set the rate policies in the usual way (maybe slider_delay = 10 for near-immediate response to shift in focus).

**Comment by homerhanumat** [comment]
Ah, just now saw your last comment.  Maybe my workaround won't be what you want:  changing focus with a mouse involves a click, so it might just as well be a click on a Submit button.  Still, it was kinda fun figuring out how to get this behavior.  And it would be just as easy to have the update occur on mouseleave, or a fixed time after mouseleave, or what-have-you ...

**Comment by fawda123** [comment]
Hm that's halfway there.  My worry with the focus out option is that users won't know that they have to click somewhere outside the slider for it to update.  Can you set it so it updates on mouseleave?  Or have an option for a fixed time after mouseleave?  Thanks!!

**Comment by homerhanumat** [comment]
Done.  You can set the time after mouseleave with the `slider_delay` argument.

**Comment by fawda123** [comment]
That's perfect, thank you!
